#!/bin/sh

BACKUP_FOLDER="/backup"
NOW=$(date "+%d")

GZIP="$(which gzip)"
MYSQLDUMP="$(which mysqldump)"

### See comments below ###
### [ ! -d $BACKUP_FOLDER ] && mkdir -p $BACKUP_FOLDER || /bin/rm -f $BACKUP_FOLDER/* ###
[ ! -d "$BACKUP_FOLDER" ] && mkdir -p "$BACKUP_FOLDER"

FILE=$BACKUP_FOLDER/backup-$NOW.sql.gz
$MYSQLDUMP -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE | $GZIP -9 > $FILE