#!/bin/sh

BACKUP_FOLDER="/snapshots"
NOW=$(date "+%d")

GZIP="$(which gzip)"
MYSQLDUMP="$(which mysqldump)"
S3CMD="$(which s3cmd)"

[ ! -d "$BACKUP_FOLDER" ] && mkdir -p "$BACKUP_FOLDER"

FILE=snapshot-$NOW.sql.gz

echo "Dumping database to $FILE"
$MYSQLDUMP -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE | $GZIP -9 > $BACKUP_FOLDER/$FILE

echo $FILE > $BACKUP_FOLDER/latest

echo "Syncing $BACKUP_FOLDER with S3 /$S3_BUCKET_PREFIX"
$S3CMD sync $BACKUP_FOLDER/ s3://$S3_BUCKET/$S3_BUCKET_PREFIX/

echo "Deleting contents of $BACKUP_FOLDER"
rm $BACKUP_FOLDER/*

echo "Complete"
